path: "E:/오픈소스SW기초 보행등 데이터 셋/target"
train: "full"
val: "full"

nc: 2
names: ["tld_green", "tld_red"]

# Hyperparameters -------------------------------------------------
translate: 0.1  # image translation (+/- fraction)
scale: 0.2  # image scale (+/- gain)
shear: 0.2  # image shear (+/- deg) from -0.5 to 0.5
perspective: 0.1  # image perspective (+/- fraction), range 0-0.001
flipud: 0.7  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mosaic: 0.3  # image mosaic (probability)
mixup: 0.1  # image mixup (probability)
# -----------------------------------------------------------------